version: '3'

services:

  pnt_app:
    
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fullchain.pem:/etc/letsencrypt/live/transparencia.ec/fullchain.pem
      - ./privkey.pem:/etc/letsencrypt/live/transparencia.ec/privkey.pem
      - ./dist:/usr/share/nginx/html
    env_file:
      - .env
    networks:
      - pnt_network

networks:
  pnt_network:
    driver: bridge
