version: '3'

services:

  pnt_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - .:/app

    environment:
      - VITE_URL_API=http://localhost:8081