version: "3"

services:
  pnt_app:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./fullchain.pem:/etc/nginx/ssl/certificates/fullchain.pem
      - ./privkey.pem:/etc/nginx/ssl/certificates/privkey.pem
      - ./dist:/etc/nginx/html
      - ./dist:/usr/share/nginx/html
    networks:
      - fundapi-backend_pnt_network

networks:
  fundapi-backend_pnt_network:
    external: true