version: '3'

services:

  pnt_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - pnt_network

    environment:
      - VITE_URL_API= http://pnt_network:8082
      - VITE_PATH_AUTH= /v1/auth

networks:
  pnt_network:
    driver: bridge
