version: "3"

services:
  pnt_webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
      #- ./certs/fullchain.pem:/etc/nginx/ssl/certificates/fullchain.pem
      #- ./certs/privkey.pem:/etc/nginx/ssl/certificates/privkey.pem
    networks:
      - pntv2-back_pnt_network

networks:
  pntv2-back_pnt_network:
    external: true
